kind: pipeline
type: docker
name: python

steps:
- name: test-python
  image: python
  commands:
  - pip install -r requirements.txt
  - pip freeze
  - ls -a
  - ls App -R -a
  - python -m pytest --cov -s -v

---

kind: pipeline
type: docker
name: docker
depends_on:
  - python

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

steps:
- name: build_and_publish
  image: docker:dind
#  privileged: true
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker login -u="jelloeater" -p="0cf0f39f8b27398b2c15e787613ed2df194c288f"
    - docker-compose build
    - docker-compose push
#  settings:
#    registry: scm.itpcon.net:444
#    username: jelloeater
#    password: 0cf0f39f8b27398b2c15e787613ed2df194c288f
#    repo: jelloeater/ApiTemplate
#    tags: latest

- name: clean
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
    - docker system prune -a --volumes -f

